### ISSUE TITLE
Abuse of notation leads to confusion

### ISSUE THREAD

**Issue by cmsquared** [Open-Astrophysics-Bookshelf/numerical_exercises#1]
Some abuse of notation in the Multidimensional Advection section leads to lack of clarity.  

In particular, the definition of the interface fluxes in Eq. 3.45 or in code [here](https://github.com/zingale/numerical_exercises/blob/master/advection/advection.tex#L786) uses the same symbol (e.g. `(ua)_{i+1/2,j}`) on both sides of the equation.  This is also confusing given the definition of `a_{i,j}` in Eq. 3.41, and the fact that you are assuming `u` (and `v`) to be constant.

**Comment by zingale** [comment]
I cleaned this up a little noting the conservative form of the advection equation explicitly and stating where we go back to just a instead of (ua)
