### ISSUE TITLE
A small typo in the book

### ISSUE THREAD

**Issue by dutta-alankar** [Open-Astrophysics-Bookshelf/numerical_exercises#11]
On page 31 in section 3.4, I think ilo=ng (assuming counting starts from 0)

```
ilo = ng #not nx
ihi = nx + ng - 1
state = np. zeros (( nx + 2*ng , nvar ))
```

**Comment by zingale** [comment]
yes, you are right.  Thanks for finding that.  I appreciate the feedback.  I'll fix it now.
